language: node_js
node_js:
  - node
services:
  - postgresql
after success:
  - npm run coverage
env:
  global:
  - NODE_ENV=test
cache:
  directories:
  - node_modules
before_script:
  - npm run migrate
