language: node_js
node_js:
 - "node"
env:
  global:
    - CC_TEST_REPORTER_ID=056f071568b921c9b169a9fa374e3487ecb9edbde6de6919197d53e71ac4f5d6

  addons:
    code_climate:
      repo_token: 056f071568b921c9b169a9fa374e3487ecb9edbde6de6919197d53e71ac4f5d6

before_script:
  - npm run migrate

install:
  - npm install

script: npm run migrate && npm test

after_success:
  -  npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
